export const Texts = {
  english: {
    iamGabriel: "I'm Gabriel",
    smallDescription: "Mobile developer focused on creating modern and efficient interfaces.",
    aboutMe: "About Me",
    descriptionAboutMe: "I develop applications with the goal of making people's lives easier and improving the way they connect with the digital world. My focus is on creating simple, fast, and intuitive experiences — those that make a difference in daily life without the user having to think much.\n\nI enjoy transforming ideas into functional and pleasant interfaces, taking care of everything from the app structure to the small details that make usage smoother. I believe that real technology is the one that solves problems, brings people closer, and makes processes lighter.\n\nAll the projects I build have a common purpose: to deliver reliable, well-thought-out solutions that offer a great experience for those who use them.",
    cardMobileDeveloper: "Mobile Development",
    descriptionCardMobileDeveloper: "Creating applications for Android and iOS focused on good performance, stability, and smooth navigation — always prioritizing usability and user experience.",
    cardArchitecture: "Architecture & Organization",
    descriptionCardArchitecture: "Structuring applications in a clear and scalable way, ensuring that the product is easy to evolve and maintain in the long term — without unnecessary technical complications.",
    cardQuality: "Quality & Reliability",
    descriptionCardQuality: "Implementing practices that prevent bugs, improve performance, and make the app safer for the end user — focusing on stability and smart testing.",
    cardEvolution: "Continuous Evolution",
    descriptionCardEvolution: "Keeping up with trends and constantly learning to deliver modern, efficient solutions aligned with the real needs of people and businesses.",
    contactMe: "Contact Me",
    experiences: "Experiences",
    descriptionExperiences: "Creating mobile and web solutions with solid architecture, consistent performance, and total focus on user experience.",
    skills: "Skills",
    projects: "Projects",
    contacts: "Contacts",
    mobileDeveloper: "Mobile Developer",
    descriptionExperienceMobileDeveloper: "Development of Android and iOS apps with React Native and TypeScript.\nFrom planning to deployment, using MVVM, Clean Architecture, and CI/CD.\nFocus on performance, stability, and great user experience.",
    frontendDeveloper: "Front-end Developer",
    descriptionExperienceFrontendDeveloper: "Development of web applications with Next.js, React, and TypeScript.\nParticipation in systems such as Booking, CRM, CMS, and internal portals.\nBest practices, componentization, and focus on performance.",
    projectFreelancer: "Freelancer Project",
    descriptionExperienceProjectFreelancer: "Website created for a photographer, with a gallery and service presentation.\nApplication of UI/UX for smooth navigation and consistent visual identity.",
    portfolioWebsite: "Portfolio Website",
    moreProjectsOnGitHub: "More projects on GitHub",
    descriptionProjects: "A selection of my featured projects, developed with a focus on performance and quality.",
    descriptionContact: "Channels for connection, networking, and tracking of my projects.",
    letsTalk: "Let's Talk",
    descriptionLetsTalk: "Always open for a good conversation. If you want to exchange ideas, talk about projects or new opportunities, just reach out to me.",
    copyright: "© 2025 Gabriel Aguiar — Mobile Developer. Crafted with clean code & creativity.",
    skillsAndTools: "Skills & Tools",
    descriptionSkillsAndTools: "Technologies I use to build my projects.",
  },
  portuguese: {
    iamGabriel: "Eu sou o Gabriel",
    smallDescription: "Desenvolvedor mobile focado em criar interfaces modernas e eficientes.",
    aboutMe: "Sobre Mim",
    descriptionAboutMe: `Desenvolvo aplicativos com o objetivo de facilitar a vida das pessoas e melhorar a forma como elas se conectam com o mundo digital. Meu foco está em criar experiências simples, rápidas e intuitivas — daquelas que fazem diferença no dia a dia sem que o usuário precise pensar muito.\n\nGosto de transformar ideias em interfaces funcionais e agradáveis, cuidando desde a estrutura do app até os pequenos detalhes que tornam o uso mais fluido. Acredito que tecnologia de verdade é aquela que resolve problemas, aproxima pessoas e torna processos mais leves.\n\nTodos os projetos que construo têm um propósito em comum: entregar soluções confiáveis, bem pensadas e que ofereçam uma ótima experiência para quem usa.`,
    cardMobileDeveloper: "Desenvolvimento Mobile",
    descriptionCardMobileDeveloper: "Criação de aplicativos para Android e iOS focados em boa performance, estabilidade e uma navegação fluida — sempre priorizando usabilidade e experiência do usuário.",
    cardArchitecture: "Arquitetura & Organização",
    descriptionCardArchitecture: "Estruturando aplicativos de forma clara e escalável, garantindo que o produto seja fácil de evoluir e manter no longo prazo — sem complicação técnica desnecessária.",
    cardQuality: "Qualidade & Confiabilidade",
    descriptionCardQuality: "Implementação de práticas que evitam bugs, melhoram o desempenho e deixam o app mais seguro para o usuário final — com foco em estabilidade e testes inteligentes.",
    cardEvolution: "Evolução Contínua",
    descriptionCardEvolution: "Acompanhando tendências e aprendendo constantemente para entregar soluções modernas, eficientes e alinhadas com as necessidades reais das pessoas e das empresas.",
    contactMe: "Entre em contato comigo",
    experiences: "Experiências",
    descriptionExperiences: "Criando soluções mobile e web com arquitetura sólida, performance consistente e foco total na experiência do usuário.",
    skills: "Habilidades",
    projects: "Projetos",
    contacts: "Contatos",
    mobileDeveloper: "Desenvolvedor Mobile",
    descriptionExperienceMobileDeveloper: "Desenvolvimento de apps Android e iOS com React Native e TypeScript.\nAtuação do planejamento ao deploy, usando MVVM, Clean Architecture e CI/CD.\nFoco em performance, estabilidade e ótima experiência do usuário.",
    frontendDeveloper: "Desenvolvedor Front-end", 
    descriptionExperienceFrontendDeveloper: "Desenvolvimento de aplicações web com Next.js, React e TypeScript.\nParticipação em sistemas como Booking, CRM, CMS e Portais internos.\nBoas práticas, componentização e foco em performance.",
    projectFreelancer: "Projeto Freelancer",
    descriptionExperienceProjectFreelancer: "Site criado para um fotógrafo, com galeria e apresentação de serviços.\nAplicação de UI/UX para navegação fluida e identidade visual consistente.",
    portfolioWebsite: "Website de Portfólio",
    moreProjectsOnGitHub: "Mais projetos no GitHub",
    descriptionProjects: "Uma seleção dos meus projetos em destaque, desenvolvidos com foco em performance e qualidade.",
    descriptionContact: "Canais para conexão, networking e acompanhamento dos meus projetos.",
    letsTalk: "Fale comigo",
    descriptionLetsTalk: "Sempre aberto para uma boa conversa. Se quiser trocar ideias, falar sobre projetos ou novas oportunidades, é só me chamar.",
    copyright: "© 2025 Gabriel Aguiar — Desenvolvedor Mobile. Criado com código limpo & criatividade.",
    skillsAndTools: "Habilidades & Ferramentas",
    descriptionSkillsAndTools: "Tecnologias que utilizo para construir meus projetos.",
  },
}